# Generated by Django 4.2.11 on 2024-04-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='photo_reference',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
